version: 0.0
os: windows
files:
  - source:  /
    destination: c:\spring
file_exists_behavior: OVERWRITE

permissions:
  -object: /
  pattern: "**"

hooks:
  ApplicationStop:
    - location: stop_server.ps1
      timeout: 30
  ApplicationStart:
    - location: start_server.ps1
      timeout: 60


