version: 0.0
os: windows
files:
  - source:  /
    destination: c:\spring
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop_server.ps1
      timeout: 100
  ApplicationStart:
    - location: scripts/start_server.ps1
      timeout: 300


