version: 0.0
os: windows
files:
  - source:  /
    destination: c:\spring
file_exists_behavior: OVERWRITE

permissions:
  -object: /
  pattern: "**"
  owner: ec2-user
  group: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/stop_server.ps1
      timeout: 30
  ApplicationStart:
    - location: scripts/start_server.ps1
      timeout: 60


